baseURL = "http://example.org/"
languageCode = "en-us"
title = "Bougiefever Blog"

[permalinks]
    blog = "/:filename/"

[menu]
    [[menu.main]]
        name = "Home"
        pre = "home" 
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Blog"
        pre = "edit"
        url = "/blog/"
        weight = 2
    [[menu.main]]
        name = "Tags"
        pre = "tag"
        url = "/tags/"
        weight = 3

[params]
    dateFormat = "Jan 25, 2019"
    homeText = "Talking about technology"

[taxonomies]
    tag = "tags"
